### ISSUE TITLE
analog screenlock clock collapses with ambient display new notifications

### ISSUE THREAD

**Issue by vincentvidal** [Descendant/rom_status#7]
**Describe the bug**
The new analog screenlock clock collapses with ambient display new notifications.

**To Reproduce**
1. Select Settings -> Display -> Ambient display -> New notifications
2. Send yourself an SMS and quiclky turn off the device
3. Wait for the screen being awaken by the notifcation

**Expected behavior**
The notification should appear below the clock.

**Smartphone (please complete the following information):**
 - Device: Xiaomi MI8 SE
 - Descendant Version: OneDotThree
 - Treble support type: OEM
 - Gapps: Yes

**Comment by Dil3mm4** [comment]
Thanks for the report, I'll look at it.

**Comment by Dil3mm4** [comment]
Solved by https://github.com/Descendant/frameworks_base/commit/61c8c8df7fd9ed5b81879c1c32d3eb2c7b29f6cf

Will be available in next release.

**Comment by Dil3mm4** [comment]
Re-shipped OneDotThree images with the fix.

**Comment by vincentvidal** [comment]
I'm sorry, but I still have the analog clock collapsing with notifications. It also collapses a bit with the date on lock screen, see screenshot. Many thanks for your efforts though...
![image](https://user-images.githubusercontent.com/24563559/47069589-957a2880-d1ef-11e8-82f5-f5ecf781d642.png)

**Comment by Dil3mm4** [comment]
Confirmed and will be fixed on OneDotFour.
